INSERT INTO regions (region_id, name) VALUES (1, 'América del Norte');
INSERT INTO regions (region_id, name) VALUES (2, 'América del Sur');
INSERT INTO regions (region_id, name) VALUES (3, 'Europa');
INSERT INTO regions (region_id, name) VALUES (4, 'África');
INSERT INTO regions (region_id, name) VALUES (5, 'Asia');
INSERT INTO regions (region_id, name) VALUES (6, 'Oceanía');
INSERT INTO regions (region_id, name) VALUES (7, 'Antártida');
INSERT INTO regions (region_id, name) VALUES (8, 'Medio Oriente');
INSERT INTO regions (region_id, name) VALUES (9, 'Sudeste Asiático');
INSERT INTO regions (region_id, name) VALUES (10, 'América Central');
INSERT INTO clients ( name, surname, email, created_at, region_id) VALUES ('Juan', 'Pérez', 'juan.perez@example.com', '2024-03-06', 1);
INSERT INTO clients (name, surname, email, created_at, region_id) VALUES ('María', 'Gómez', 'maria.gomez@example.com', '2024-03-06',2);
INSERT INTO clients (name, surname, email, created_at, region_id) VALUES ('Carlos', 'Rodríguez', 'carlos.rodriguez@example.com', '2024-03-06',3);
INSERT INTO clients (name, surname, email, created_at,region_id) VALUES ( 'Laura', 'Fernández', 'laura.fernandez@example.com', '2024-03-06',4);
INSERT INTO clients (name, surname, email, created_at,region_id) VALUES ( 'Alejandro', 'López', 'alejandro.lopez@example.com', '2024-03-06',5);
INSERT INTO clients (name, surname, email, created_at,region_id) VALUES ('Carmen', 'Martínez', 'carmen.martinez@example.com', '2024-03-06',6);
INSERT INTO clients (name, surname, email, created_at,region_id) VALUES ('Pedro', 'García', 'pedro.garcia@example.com', '2024-03-06',7);
INSERT INTO clients (name, surname, email, created_at,region_id) VALUES ('Ana', 'Sánchez', 'ana.sanchez@example.com', '2024-03-06',8);
INSERT INTO clients (name, surname, email, created_at,region_id) VALUES ('David', 'Díaz', 'david.diaz@example.com', '2024-03-06',9);
INSERT INTO clients (name, surname, email, created_at,region_id) VALUES ('Elena', 'Hernández', 'elena.hernandez@example.com', '2024-03-06',10);
