INSERT INTO clients ( name, surname, email, created_at, region_id) VALUES ('Juan', 'Pérez', 'juan.perez@example.com', '2024-03-06', 1);
INSERT INTO clients (name, surname, email, created_at, region_id) VALUES ('María', 'Gómez', 'maria.gomez@example.com', '2024-03-06',2);
INSERT INTO clients (name, surname, email, created_at, region_id) VALUES ('Carlos', 'Rodríguez', 'carlos.rodriguez@example.com', '2024-03-06',3);
INSERT INTO clients (name, surname, email, created_at,region_id) VALUES ( 'Laura', 'Fernández', 'laura.fernandez@example.com', '2024-03-06',4);
INSERT INTO clients (name, surname, email, created_at,region_id) VALUES ( 'Alejandro', 'López', 'alejandro.lopez@example.com', '2024-03-06',5);
INSERT INTO clients (name, surname, email, created_at,region_id) VALUES ('Carmen', 'Martínez', 'carmen.martinez@example.com', '2024-03-06',6);
INSERT INTO clients (name, surname, email, created_at,region_id) VALUES ('Pedro', 'García', 'pedro.garcia@example.com', '2024-03-06',7);
INSERT INTO clients (name, surname, email, created_at,region_id) VALUES ('Ana', 'Sánchez', 'ana.sanchez@example.com', '2024-03-06',8);
INSERT INTO clients (name, surname, email, created_at,region_id) VALUES ('David', 'Díaz', 'david.diaz@example.com', '2024-03-06',9);
INSERT INTO clients (name, surname, email, created_at,region_id) VALUES ('Elena', 'Hernández', 'elena.hernandez@example.com', '2024-03-06',10);
